name: 'PR Merged: Release'
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - '.github/**'
    types: [opened, synchronize, reopened, closed] 
    branches:
    - master
    - stage

permissions:
  contents: write      

jobs:
  build:
   name: Build and Test Application
   uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Build-Test.yml@main
   with:
      platform: "java"
      command: "mvn -B package --file pom.xml"
      
  create_release:
    if: github.event.pull_request.merged == true
    needs: build
    name: Create Tag and Release
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Create-Tag-Release.yml@main
    with:
     source_branch: ${{ github.base_ref }}
